server:
  port: 8301
spring:
  application:
    name: spring-cloud-application
  config:
    import: configserver:http://localhost:8300
management:
  endpoints:
    web:
      exposure:
        include: "*"